# Jekyll static site generator configuration
title: Awesome Ancient Egypt
description: A curated list of online resources about Ancient Egypt
theme: jekyll-theme-cayman
# available themes: https://pages.github.com/themes/
show_downloads: false
google_analytics: G-68RCD0YSDS
